#if !defined(RADIOLIB_LR2021_TYPES_H)
#define RADIOLIB_LR2021_TYPES_H

#include "../../TypeDef.h"

#if !RADIOLIB_EXCLUDE_LR2021

#include "LR2021_commands.h"

/*!
  \struct LR2021LrFhssHopTableEntry_t
  \brief Structure to save information about LR-FHSS hopping table entry.
*/
struct LR2021LrFhssHopTableEntry_t {
  bool hoppingEnable;
  bool convertFreq;
  uint16_t packetLen;
  uint8_t numUsedFrequencies;
  uint8_t numHoppingBlocks;
  uint32_t freq;
  uint16_t numSymbols;
};

/*!
  \struct LR2021LoRaSideDetector_t
  \brief Structure to configure multi-SF detection
*/
struct LR2021LoRaSideDetector_t {
  /*! \brief Spreading factor value */
  uint8_t sf;
  
  /*! \brief Low datarate optimization enabled for this detector */
  bool ldro;
  
  /*! \brief IQ inversion for this detector */
  bool invertIQ;

  /*! \brief LoRa sync word for this detector */
  uint8_t syncWord;
};

/*!
  \struct LR2021BleConfig_t
  \brief Configuration of the LR2021 Bluetooth LE physical layer.

  This is deliberately not the shared PhysicalLayer ConfigBLE_t: that one describes the
  SX128x, which exposes BLE as a plain GFSK variant (bit rate, deviation, shaping).
  The LR2021 has a dedicated BLE packet engine instead, so what has to be configured is
  the PHY mode plus the channel-dependent access address, CRC seed and whitening init.

  Only the physical layer is provided by the chip. The PDU header is not generated by
  the transceiver - it has to be built by the host and written to the FIFO as the first
  bytes of the payload (see LR2021 datasheet section 15.2).
*/
struct LR2021BleConfig_t {
  /*! \brief Carrier frequency in MHz. Defaults to 2402.0 MHz (advertising channel 37). */
  float frequency = 2402.0;

  /*! \brief BLE PHY, one of RADIOLIB_LR2021_BLE_PHY_*. Defaults to LE 1M. */
  uint8_t phy = RADIOLIB_LR2021_BLE_PHY_1M;

  /*! \brief Channel PDU type, one of RADIOLIB_LR2021_BLE_CHANNEL_TYPE_*. Defaults to advertising. */
  uint8_t channelType = RADIOLIB_LR2021_BLE_CHANNEL_TYPE_ADV;

  /*!
    \brief Whitening initial value. This is channel dependent - use LR2021::bleWhiteningInit()
    to derive it from a BLE channel index. Set to RADIOLIB_LR2021_BLE_WHITENING_OFF to disable
    whitening (test mode). Defaults to the value for channel 37 (0x53).
  */
  uint8_t whiteningInit = 0x53;

  /*! \brief Access address (BLE sync word). Defaults to the advertising access address. */
  uint32_t accessAddress = RADIOLIB_LR2021_BLE_ADV_ACCESS_ADDRESS;

  /*! \brief 24-bit CRC seed. Defaults to the advertising CRC init value. */
  uint32_t crcInit = RADIOLIB_LR2021_BLE_ADV_CRC_INIT;

  /*! \brief Whether the 3 CRC bytes are appended to the payload in the Rx FIFO. Defaults to false. */
  bool crcInFifo = false;

  /*! \brief Output power in dBm. Defaults to 10 dBm. */
  int8_t power = 10;
};

/*!
  \struct paTableEntry_t
  \brief This structure is used as entry in the PA lookup table, 
  to optimize PA configuration for minimum power consumption.
*/
struct __attribute__((packed)) LR2021PaTableEntry_t {
  uint8_t paDutyCycle: 4;
  uint8_t paSlices: 4;
  int8_t paVal;
};

#endif

#endif
